name: hello
description: A 'hello' server example with package:shelf to run with Docker.
publish_to: none # Not intended for publishing to pub.dev.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.0.0
  shelf_router: ^1.0.0

dev_dependencies:
  http: ^0.13.0
  test: ^1.15.0
  test_process: ^2.0.0
